name: QA

on: [push]

jobs:
  build:

    strategy:
      max-parallel: 3
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint
      run: |
        black --check --quiet ddconfig tests
        isort -rc --check-only ddconfig tests
        pylint ddconfig tests
    - name: Test with tox/pytest
      run: tox
